# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a951f17c0b6487691e97f89adbaf72f519db8484210a24ba21f2c2ab7923942091940f5e8a17cb4dfa8d125840ff169ad2432a8552eedf08b5a3d2a51dab5b86

test:
  secret_key_base: b0e62a21577aa9e4d6d16aff4a0e6fda673ac6ed590542a06d0ee1ba6c2f54adea88f6fa3899be699bad67e4a24af4e3b51a4870b33aaf9023586170095dcf2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
